### PR TITLE
add form__fieldset--error

### PR DESCRIPTION
**Pull request by kenglxn**
attempt to fix red border as in the zeplin design https://app.zeplin.io/project/565f0961b5cf3de75ae16547/screen/5819e6a22d1bece451400cb2

Not sure I did the changes right. Could not get the gulp build to work without it changing a bunch of stuff, so I edited src and dist manually.

connected to https://github.com/gramo-org/echo/issues/1853

### CODE REVIEW

**Comment by kenglxn** [comment]
result 
image

**Comment by fredlesser** [comment]
@kenglxn we've got a class .form__fieldset--has-error :) Maybe we can just use that? I can change the CSS if needs be.

**Comment by kenglxn** [comment]
excellent suggestion. Can you fix it for me?

**Comment by kenglxn** [comment]
works like a charm :). will use has-errors instead

**Pull request closed without merging**
