### PR TITLE
Fix updated login page styles

### PR DESCRIPTION
**Pull request by rreckonerr**
Switch to English link is hidden under the cookies consent banner.

### CODE REVIEW

**Comment by fredlesser** [comment]
@rreckonerr I wonder why styles.css has changed. As you've only changed minside css, styles.css which is Echo's stylesheet shouldn't have been changed. Can you look into it?

**Comment by rreckonerr** [comment]
@fredlesser that's exactly what I was talking about! Running gulp from my laptop somehow removes some webkit styles throughout the app. Do you know anyone who is able to help me with gulp configuration

**Comment by fredlesser** [comment]
@rreckonerr try editing the gulpfile at the autoprefixer part and going from eg last 2 versions to last 3. See if that makes a difference

**Comment by rreckonerr** [comment]
@fredlesser right now autoprefixer is configured to support last 6 versions. If I replace it with 3, even more styles get removed

**Pull request merged**
