### PR TITLE
Change the background colour of the horizontal rule text on login page

### PR DESCRIPTION
**Pull request by skalar-bcawkwell**
It would be nice to inherit the colour from the grandparent, however that is not
possible in pure CSS. Since this is only used on the login page, this will have
to do for now.

### CODE REVIEW

**Comment by skalar-bcawkwell** [comment]
@kjellm Is there some version that will need to be bumped in https://github.com/gramo-org/echo-front to get the latest changes from this repo?

**Comment by kjellm** [comment]
A bit embarrassing that I don't know for sure, but the version is defined here:

https://github.com/gramo-org/echo-front/blob/7268a12e04dd435626b2a95fd308d9937c00c330/bower.json#L7

@acskalar Do you know how we update to newest UI-kit?

**Comment by acskalar** [comment]
I think it is changing the bower.json file. However this changes min-side css, so you would need to update min-side not echo-front?

**Comment by kjellm** [comment]
Yes, my bad 🤦

**Pull request merged**
